services:
  - type: web
    name: poketd-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
